/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlektstreIndexRouteImport } from './routes/slektstre/index'
import { Route as ProfilIndexRouteImport } from './routes/profil/index'
import { Route as OppskrifterIndexRouteImport } from './routes/oppskrifter/index'
import { Route as KartIndexRouteImport } from './routes/kart/index'
import { Route as HistorieIndexRouteImport } from './routes/historie/index'
import { Route as ArkivIndexRouteImport } from './routes/arkiv/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlektstreIndexRoute = SlektstreIndexRouteImport.update({
  id: '/slektstre/',
  path: '/slektstre/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const OppskrifterIndexRoute = OppskrifterIndexRouteImport.update({
  id: '/oppskrifter/',
  path: '/oppskrifter/',
  getParentRoute: () => rootRouteImport,
} as any)
const KartIndexRoute = KartIndexRouteImport.update({
  id: '/kart/',
  path: '/kart/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorieIndexRoute = HistorieIndexRouteImport.update({
  id: '/historie/',
  path: '/historie/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArkivIndexRoute = ArkivIndexRouteImport.update({
  id: '/arkiv/',
  path: '/arkiv/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/historie/': typeof HistorieIndexRoute
  '/kart/': typeof KartIndexRoute
  '/oppskrifter/': typeof OppskrifterIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/slektstre/': typeof SlektstreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arkiv': typeof ArkivIndexRoute
  '/historie': typeof HistorieIndexRoute
  '/kart': typeof KartIndexRoute
  '/oppskrifter': typeof OppskrifterIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/slektstre': typeof SlektstreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arkiv/': typeof ArkivIndexRoute
  '/historie/': typeof HistorieIndexRoute
  '/kart/': typeof KartIndexRoute
  '/oppskrifter/': typeof OppskrifterIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/slektstre/': typeof SlektstreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arkiv/'
    | '/historie/'
    | '/kart/'
    | '/oppskrifter/'
    | '/profil/'
    | '/slektstre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arkiv'
    | '/historie'
    | '/kart'
    | '/oppskrifter'
    | '/profil'
    | '/slektstre'
  id:
    | '__root__'
    | '/'
    | '/arkiv/'
    | '/historie/'
    | '/kart/'
    | '/oppskrifter/'
    | '/profil/'
    | '/slektstre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArkivIndexRoute: typeof ArkivIndexRoute
  HistorieIndexRoute: typeof HistorieIndexRoute
  KartIndexRoute: typeof KartIndexRoute
  OppskrifterIndexRoute: typeof OppskrifterIndexRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
  SlektstreIndexRoute: typeof SlektstreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slektstre/': {
      id: '/slektstre/'
      path: '/slektstre'
      fullPath: '/slektstre/'
      preLoaderRoute: typeof SlektstreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppskrifter/': {
      id: '/oppskrifter/'
      path: '/oppskrifter'
      fullPath: '/oppskrifter/'
      preLoaderRoute: typeof OppskrifterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kart/': {
      id: '/kart/'
      path: '/kart'
      fullPath: '/kart/'
      preLoaderRoute: typeof KartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historie/': {
      id: '/historie/'
      path: '/historie'
      fullPath: '/historie/'
      preLoaderRoute: typeof HistorieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arkiv/': {
      id: '/arkiv/'
      path: '/arkiv'
      fullPath: '/arkiv/'
      preLoaderRoute: typeof ArkivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArkivIndexRoute: ArkivIndexRoute,
  HistorieIndexRoute: HistorieIndexRoute,
  KartIndexRoute: KartIndexRoute,
  OppskrifterIndexRoute: OppskrifterIndexRoute,
  ProfilIndexRoute: ProfilIndexRoute,
  SlektstreIndexRoute: SlektstreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
